apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-storage-pvc-longhorn-rwx
  namespace: dify
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
