apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-plugin-storage-pvc-longhorn
  namespace: dify
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
