apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-plugin-daemon
  namespace: dify
  labels:
    app: dify-plugin-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-plugin-daemon
  template:
    metadata:
      labels:
        app: dify-plugin-daemon
    spec:
      containers:
      - name: plugin-daemon
        image: langgenius/dify-plugin-daemon:0.2.0-local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
          name: http
        - containerPort: 5003
          name: debug
        env:
        # Database credentials from Secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: DB_PASSWORD
        # Redis credentials from Secret
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: REDIS_USERNAME
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: REDIS_PASSWORD
        # Plugin daemon specific environment variables
        - name: DB_DATABASE
          value: "dify_plugin"
        - name: SERVER_PORT
          value: "5002"
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DAEMON_KEY
        - name: MAX_PLUGIN_PACKAGE_SIZE
          value: "52428800"
        - name: PPROF_ENABLED
          value: "false"
        - name: DIFY_INNER_API_URL
          value: "http://dify-api-service.dify.svc.cluster.local:5001"
        - name: DIFY_INNER_API_KEY
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DIFY_INNER_API_KEY
        - name: PLUGIN_REMOTE_INSTALLING_HOST
          value: "0.0.0.0"
        - name: PLUGIN_REMOTE_INSTALLING_PORT
          value: "5003"
        - name: PLUGIN_WORKING_PATH
          value: "/app/storage/cwd"
        - name: FORCE_VERIFYING_SIGNATURE
          value: "true"
        - name: PYTHON_ENV_INIT_TIMEOUT
          value: "120"
        - name: PLUGIN_MAX_EXECUTION_TIMEOUT
          value: "600"
        - name: PLUGIN_STORAGE_TYPE
          value: "local"
        - name: PLUGIN_STORAGE_LOCAL_ROOT
          value: "/app/storage"
        - name: PLUGIN_INSTALLED_PATH
          value: "plugin"
        - name: PLUGIN_PACKAGE_CACHE_PATH
          value: "plugin_packages"
        - name: PLUGIN_MEDIA_CACHE_PATH
          value: "assets"
        # Shared environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: dify-config
        volumeMounts:
        - name: plugin-storage
          mountPath: /app/storage
      volumes:
      - name: plugin-storage
        persistentVolumeClaim:
          claimName: dify-plugin-storage-pvc-longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: dify-plugin-daemon-service
  namespace: dify
spec:
  type: ClusterIP
  selector:
    app: dify-plugin-daemon
  ports:
  - name: http
    protocol: TCP
    port: 5002
    targetPort: http
  - name: debug
    protocol: TCP
    port: 5003
    targetPort: debug
